### ISSUE TITLE
[UI] SP Registration. Create new institution 

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Backend#1171]
**Environment:**Windows 11, 64 b.; Google Chrome 114.0.5735.199.
**Reproducible:** always.

**Preconditions**
1. User is not logged into website
2. Go to main page https://oos.dmytrominochkin.cloud/#/

**Steps to reproduce**
1. Click on "УВІЙТИ/ЗАРЕЄСТРУВАТИСЯ" button in top right corner
4. Click on "Зареєструватися" hyperlink
5. Choose a "Надавач послуг" option

**Actual result** 
1. Spelling mistake. Should be "По батькові"
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/a2051637-464c-4f8d-b195-1fce9c5a0bf3)
2. There are two different design styles of the address field. On "Реєстрація" page:
 ![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/2ec9b08b-4ad7-4835-8393-d1af6de7b5d5)
On "Реєстрація нового закладу" page, section "Інформація про заклад"

![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/daab350a-dc62-477e-a9d3-b708ddf7fe12)

3.On "Реєстрація" page
 (Steps to reproduce: 1. Fill in all required fields with correct data, 2. Enter invalid data in the "Телефон" field. 3. Сlick on the button "Зареєструватися")

Punctuation mistake. Error messages require a comma after the word "перевірте" and after the word "ласка" in Error messages:
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/2eb44af3-22c8-45f7-acbe-985ff0edfe24)

5. Section "Інформація про заклад" 

(Steps to reproduce: 1.Click on "УВІЙТИ/ЗАРЕЄСТРУВАТИСЯ" button in top right corner, 2. Click on "Зареєструватися" hyperlink, 3. Enter valid data into mandatory fields, 4. Click on "Зареєструватися" button, 5. Go on the "Інформація про заклад" section on the page (Click on the button "Вхід в позашкілля")

Spelling mistake. Should be "категорію":
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/f703e6b1-ec91-4bfa-b6e7-d8fbe7155c07)

6. Section "Контакти" 

(Steps to reproduce: 1.Click on "УВІЙТИ/ЗАРЕЄСТРУВАТИСЯ" button in top right corner, 2. Click on "Зареєструватися" hyperlink, 3. Enter valid data into mandatory field, 4. Click on "Зареєструватися" button, 5. Go on the "Інформація про заклад" section on the page ( by clicking on the button "Вхід в позашкілля"), 6. Enter valid data into all mandatory fields, 7. Click on the "Далі" button)

There are extra spaces between the words "контакти" and a comma,  in error messages under fields "Вулиця" and  "Будинок"
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/3e142c24-68cd-4aae-81f5-1ad51d0d3658)

7. Should be "Збігається з юридичною адресою"
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/5f12ebd1-5833-46d2-868c-5f7f4dccf4d1)

**Expected result**
All UI elements correspond to design. 

**User story and test case links**
[Test case](https://jira.softserve.academy/browse/OS-575)

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Low"), Type ("UI").

**Comment by doliinyk** [comment]
Issue of spelling mistakes on first register page persists on backend (because it is comes from authorization server), what includes steps 1-4.
Steps 5-7 have been fixed in ita-social-projects/OoS-Frontend#2186

**Comment by OlenaYakubova** [comment]
Only points 1-4.
Points 5-7 have been fixed on the frontend.
