### ISSUE TITLE
[Ministry admin] The Administrator of the region and the administrator of the OTG are not created.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Backend#1182]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Log in as Ministry admin ("Email" = '[kisof90893@inkiny.com](mailto:kisof90893@inkiny.com)', "password" = 'KW_87b2U')

**Steps to reproduce**
1. Go to "Адміністрування" on the top right corner drop down list.
2. Click on "Адміністратори" tab.
3. Click the "Додати" button.
4. Choose "Адміністратор області" or "Адміністратор ОТГ" from the drop-down menu.

**Actual result**
The administrator of the ministry cannot create the administrator of the region and the administrator of the OTG.
https://drive.google.com/file/d/10x09wymv9FZF--BO2f95_fzpBOKuqcjp/view?usp=sharing

**Expected result**
When selecting an administrator of the region or an administrator of the OTG from the drop-down menu, a page for adding the selected administrator appears

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: high"), Type ("Functional"), "API" (for back-end bugs).

**Comment by doliinyk** [comment]
Will come with [PR2193 on Frontend](https://github.com/ita-social-projects/OoS-Frontend/pull/2193).
Waiting for merging [PR1189 on Backend](https://github.com/ita-social-projects/OoS-Backend/pull/1189)

**Comment by doliinyk** [comment]
Seems like it is fixed both on backend and frontend

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
