### ISSUE TITLE
[Log In] The system automatically logs out the User (ServiceProvider,Parent)

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Backend#1219]
**Environment:** Windows 11, 64 bit
Chrome 115.0.5790.171
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as a Parent (e.g."Email" = 'parent@gmail.com', "password" = 'P23juhd!o') or Service Provider (e.g."Email" = 'Sprovider@gmail.com', "password" = 'SP2789hd!o'

**Steps to reproduce**
1. Not log out from personal cabinet. Wait about 5 minutes.

**Actual result**
After 5-7 minutes of being in the personal account, the system automatically logs out the User (Parents, Service provider)
![image](https://github.com/ita-social-projects/OoS-Backend/assets/73597578/040fd81e-6fcc-4f5c-8e39-63bd3d5d0449)

**Expected result**
The User exits the personal account using the "Вийти" button.

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("High"), Type ("Functional").

**Comment by doliinyk** [comment]
Fixed on https://github.com/ita-social-projects/OoS-Frontend/pull/2242
