### ISSUE TITLE
[Admin OTG] Error 403 when the institution is blocked or unblocked by the OTG administrator.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Backend#1224]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Log in as Admin OTG ("Email" = '[jevahaj880@synclane.com](mailto:jevahaj880@synclane.com)', "password" = '?_7jrRnL')

**Steps to reproduce**
1. Go to "Адміністрування" on the top right corner drop down list.
2. Click on "Заклади" tab.
3. Select the "Нептун" institution and press the three dots at the end of the line.
4. Select "Заблокувати заклад" from the drop-down menu.
5. Enter the reason and phone number on the "Заблокувати надавача послуг?" page and click the "Підтвердити" button.
6. Select the "Дитячий табір №1" institution and press the three dots at the end of the line.
7. Select "Розблокувати заклад" from the drop-down menu.
8. Click the "Підтвердити" button.

**Actual result**
The OTG administrator cannot unlock or block the institution. Error 403.
![Screenshot_24](https://github.com/ita-social-projects/OoS-Backend/assets/115226563/382c6982-bcaa-4e60-b5c7-ad96099a3913)
![Screenshot_110](https://github.com/ita-social-projects/OoS-Backend/assets/115226563/8234d8fd-b8eb-43d6-84f2-54707ebcf120)
![Screenshot_22](https://github.com/ita-social-projects/OoS-Backend/assets/115226563/5ddfac36-7f28-4342-90fe-96a4bc80a3a2)

**Expected result**
The OTG administrator can unlock or block the institution. 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: high"), Type ("Functional"), "API" (for back-end bugs).

**Comment by ViktoriiaHrytchyna** [comment]
After rechecking bug is reprodused.

**Comment by VitaliyYuras** [comment]
> After rechecking bug is reprodused.

Try to log out and log back in.

**Comment by ViktoriiaHrytchyna** [comment]
Fixed)
