### ISSUE TITLE
[UI;Block SP]  The tooltip is not displayed in the block window of the Service Provider

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Backend#1277]
**Environment:** Windows 11, 64 bit
Chrome 117.0.5938.134
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as Region Admin (Admin OTG, Technical Admin)
3. At least one Servise provider is created

**Steps to reproduce**
1. Go to 'Адміністрування' tab
3. Click on 'Заклади' subtab
4. Click on the three vertical dots opposite any Service Provider
5. From the drop-down list, select the line "Заблокувати заклад".

**Actual result**
 The tooltip is not displayed in the block window of the Service Provider
![image](https://github.com/ita-social-projects/OoS-Backend/assets/73597578/81fc97d8-7f40-4046-b89e-244c1751a467)

**Expected result**
Should be "Вкажіть причину блокування" (https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?type=design&node-id=8625-7434&mode=design&t=Gs0gTbI6NC2ERQlU-0)

![image](https://github.com/ita-social-projects/OoS-Backend/assets/73597578/26d1e359-d133-4dbb-8f09-cff80fa21e9c)

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Low"), Type ("UI").

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2349
