### ISSUE TITLE
[Service Provider;Applications] Applications are not displayed correctly during block/unblock actions

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Backend#1284]
**Environment:** Windows 11, 64 bit
Chrome 118.0.5993.118
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as Service Provider
3. Servise provider has some applications with diferent statuses ("Підтверджено", "Заблоковано","Навчається 1-11 років" e.g.)

**Steps to reproduce**
1. Go to 'Заявки' tab
4. Verify 'Заблоковано' subtab
5. Go back to "Усі" subtat
6. Click on three vertical dots opposit unblocked application
7. Choose "Заблокувати користувача" line
8. Go to "Заблоковано" subtab

**Actual result**
1. "Заблоковано" subtab works incorectly
2. Pop-up "Користувач успішно заблокований" appears when user is unblocked.
https://app.screencast.com/8OucwqLP6KK2d

**Expected result**
1. All aplications with status "Заблоковано" should be displayed on subtab "Заблоковано". Only aplications with status "Заблоковано" should be displayed on subtab "Заблоковано"
2. Pop-up should be change to "Користувач успішно розблокований" 

**User story and test case links**
User story #496 

**Labels to be added**
"Bug", Priority ("High"), Severity ("High"), Type ("Functional").

**Comment by DKymachynskyi** [comment]
@DmyMi, this is front-end issue because in OoS-Frontend\src\app\shared\store\provider.state.ts:
`@Action(UnBlockParentSuccess)
  unBlockParentFailSuccess({ dispatch }: StateContext<ProviderStateModel>, { payload, entityType }: UnBlockParentSuccess): void 
{
    dispatch([
      new GetApplicationsByPropertyId(payload.providerId, {
        property: entityType,
        statuses: [],
        showBlocked: false,
        workshops: []
      }),
      new MarkFormDirty(false),
      new ShowMessageBar({ message: SnackbarText.blockPerson, type: 'success' })
    ]);
  }`
parameters `showBlocked: false` should be `true`,
and `message: SnackbarText.blockPerson` should be `SnackbarText.unblockPerson`.

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2296

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2296

**Comment by OlenaYakubova** [comment]
Hallo! @doliinyk , please also check this behavior: when I block one user all applications are not displayed in their tabs, but applications with the status "blocked" appear. When I unblock one user, all blocked applications disappear, but applications with all other statuses appear. Thank you!
https://app.screencast.com/2GLzdbfAlhwK8

**Comment by doliinyk** [comment]
> Hallo! @doliinyk , please also check this behavior: when I block one user all applications are not displayed in their tabs, but applications with the status "blocked" appear. When I unblock one user, all blocked applications disappear, but applications with all other statuses appear. Thank you! https://app.screencast.com/2GLzdbfAlhwK8

Hi, it is not an issue - because you are blocking the application of a child and all children belong to **only parent** in your case, that parent is blocked and all his applications are blocked also 🙂
You can try add applications from other parents and they won't be blocked

**Comment by doliinyk** [comment]
Hi @OlenaYakubova, it is completely fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2302
