### ISSUE TITLE
[Region Admin cabinet, administration] Region Admin and Admin OTG can not block/unblock/approve/send for editing Service providers

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Backend#1340]
**Environment:** Windows 11, 64 bit
Google Chrome 120.0.6099.130
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as Admin OTG or Regional Admin
3. Admins from preconditions have at least one Servise provider

**Steps to reproduce**
1. Go to 'Адміністрування' tab (tab 'Заклади' is opened by default)
2. Click on three vertical dots opposite Service provider
3. Select option block/unblock/approve/send for editing 
4. Click on 'Підтвердити' button

**Actual result**
Region Admin and Admin OTG cann't block/unblock/approve/send for editing Service providers
https://app.screencast.com/gBl9rw5wUrQfY
https://app.screencast.com/9ogRdRvFOEAtC

**Expected result**
Admin OTG and Region admin can take actions according to the permissions matrix.

**User story and test case links**
User stories: #479 , #865 

**Labels to be added**
"Bug", Priority ("High"), Severity ("High"), Type ( "Functional").

**Comment by andriitsylia** [comment]
The Provider\StatusUpdate endpoint was moved to a new one PublicProviderController\StatusUpdate for the state providers (to approve or send it for editing) and to a new one PrivateProviderController\LicenseStatusUpdate for the private providers.
