### ISSUE TITLE
Create endpoints for Cities

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Backend#163]
Create a CRUD endpoints for Ukrainian cities.
1. GET data endpoints should be available for everyone (anonymous)
2. CREATE, PUT, DELETE - admin only
3. Implement an ability to filter cities by name (minimum 3 letters). Should return a list of cities whose name starts with the entered string. If there is no match - should return an empty list.
4. Base list of cities should be prepopulated with data:
oblast, raion, City name, coordinates (lat/lon)
Approximate list of cities (will be updated next week): [ua-list.csv](https://github.com/ita-social-projects/OoS-Backend/files/6675682/ua-list.csv) (utf-8 encoding)

**Comment by v-ivanchuk** [comment]
[Instruction for Cities DB population.docx](https://github.com/ita-social-projects/OoS-Backend/files/6740525/Instruction.for.Cities.DB.population.docx)
