### ISSUE TITLE
Add Keywords to Workshop

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Backend#172]
**Story link**
[#55 Story](https://github.com/ita-social-projects/OoS-Backend/issues/55)

### Task description
Add `keywords` field to workshop

### To do 
1. - [ ] Add `keywords` field to workshop.
2. - [ ] The `keywords` are going to be sent from frontend (and need to be returned to frontend) as a list of strings during workshop create and workshop update. Need to verify the list has no duplicate strings.
3. - [ ] The list of strings needs to be saved to database as text using some separator.

**Comment by v-ivanchuk** [comment]
Successfully tested via Postman:
![Create](https://user-images.githubusercontent.com/73526573/124792145-68e53c80-df55-11eb-9d9b-745df67969d2.JPG)
![Update](https://user-images.githubusercontent.com/73526573/124792157-6d115a00-df55-11eb-87fa-82d6b00c1606.JPG)
