### ISSUE TITLE
Page of a section/group/class in Cabinet SP

### ISSUE THREAD

**Issue by AnatoliiIvantsov** [ita-social-projects/OoS-Backend#174]
as a user (Service Provider), I want to see all my information in the System concerning section/groupe/class in order to be able to check, update and correct it

Description
https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-Dev-Team?node-id=767%3A27
https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-Dev-Team?node-id=805%3A28

Preconditions:
    • A user has an account in the application and data of a section/group/class entered into the system

Acceptance Criteria

    1. The "Гуртки" page is a tab in a SP Cabinet
    2. A tab “Гуртки” should contain  fields of output information (entered into the database by the service provider when registering in the system (US 55) or in its cabinet)
    3. Users with Main logins have the ability to enter and correct all data in the Cabinet SP (including all classes / sections)
    4. Users with Helper logins have the ability to add a new class / section by himself and correct all data related to the class / section entered into the system by them or associated with their access by Main login (US 89).
    5. By clicking on the button “pen” or “trash”, users can edit information or delete class/section:

![image](https://user-images.githubusercontent.com/77727618/123393505-d5039000-d5a6-11eb-8bb6-417e0fe53f75.png)

### Tasks 
1. - [ ] sample task.

**Comment by Nikita-Babenko** [comment]
If the workshop deletes someone and at the same time another user tries to go to the page of this group: Display service message "Гурток було видалено"
