### ISSUE TITLE
Update nvarchar field length for entities

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Backend#185]
Update `nvarchar` field length instead of `nvarchar(max)` for:
1. Providers. Reference [issue#54](https://github.com/ita-social-projects/OoS-Backend/issues/54)
2. Workshops. Reference [issue#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
3. Teachers. Reference [issue#55](https://github.com/ita-social-projects/OoS-Backend/issues/55) section 4 & 5
4. Addresses. Reference [issue#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
5. Social groups (name limit to 100)
6. [User](https://github.com/ita-social-projects/OoS-Backend/blob/develop/OutOfSchool/OutOfSchool.DataAccess/Models/User.cs) as per [recommendations](https://joshthecoder.com/2020/04/28/max-data-types-in-aspnet-core-identity-schema.html)
7. Make sure if any entity has a key for UserId the field is capped at `nvarchar(450)`

**Comment by SergeyNovitsky** [comment]
done
