### ISSUE TITLE
 Rating the workshop

### ISSUE THREAD

**Issue by Koshelenko-Tamara** [ita-social-projects/OoS-Backend#211]
**As a** user **I want to** rate the workshop **so that** the information about the quality of service will be available for users and service providers.
**Description**
Workshop rating process available for registered users. 

**Precondition**
The user must be registered. A single user is allowed to rate a workshop only ONCE. 

### Acceptance Criteria
1. When opening a card of a workshop a user can see the tab called "РЕЙТИНГ". 

<img width="486" alt="Screenshot 2021-07-09 at 12 47 09" src="https://user-images.githubusercontent.com/77809312/125066038-38b7ae00-e0bb-11eb-9804-420c647680a8.png">
2. Tapping on the tab "РЕЙТИНГ", he will be redirected to a window:

<img width="966" alt="Screenshot 2021-07-09 at 13 12 57" src="https://user-images.githubusercontent.com/77809312/125066508-be3b5e00-e0bb-11eb-9be9-5937bab5c23f.png">

3. Pressing the button "ЗАЛИШИТИ ОЦІНКУ" a pop-up window appears:

<img width="482" alt="Screenshot 2021-07-09 at 12 48 01" src="https://user-images.githubusercontent.com/77809312/125067608-29396480-e0bd-11eb-9d10-ac405e70f5fc.png">

4. The rating starts from 1 star to 5 stars (1 is the worst rate). Tapping on the stars, choosing the quantity of them the user rates the workshop according to his point of view. 
5. When the stars are chosen he must click on "НАДІСЛАТИ". 
6. If the user doesn't want to proceed with the rating process, he must click on "СКАСУВАТИ". 
7. The total amount of the stars in rating will be calculated automatically and shown as an average number on the workshop card. 

<img width="489" alt="Screenshot 2021-07-09 at 14 04 05" src="https://user-images.githubusercontent.com/77809312/125069467-73bbe080-e0bf-11eb-8562-e325629d51c6.png">

8. If the user wants to see all the rates of a particular workshop, he must click on the button "ПЕРЕГЛЯНУТИ ВСІ ОЦІНКИ"

<img width="915" alt="Screenshot 2021-07-09 at 14 13 28" src="https://user-images.githubusercontent.com/77809312/125069869-ffce0800-e0bf-11eb-99eb-bb335f4261a6.png">
9. If the user wants to see the total rating of a whole institution (service provider), he must choose the tab "ПРО ЗАКЛАД", where he will find the total rating of all the workshops within the chosen service provider.

<img width="904" alt="Screenshot 2021-07-09 at 14 16 51" src="https://user-images.githubusercontent.com/77809312/125070465-aadec180-e0c0-11eb-89cd-e7ece6f8e9c4.png">

**Comment by v-ivanchuk** [comment]
Done from backend side

**Comment by hanna-lenko** [comment]
Updates:
'Рейтинг' tab = 'Відгуки' tab
Button "ПЕРЕГЛЯНУТИ ВСІ ОЦІНКИ" displays if the workshop has more than 3 rates
Mockups: https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=4313%3A2319 
https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=4313%3A2639
