### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by kechandrew** [ita-social-projects/OoS-Backend#23]
As a user, I want to find children's classes through the "search" button, so that I can choose interesting classes.

**Description**
Mockup https://ninjamock.com/s/QJ1HFHx

Preconditions:
- A user is registered;
- All classes are listed in a database;

Assumption:
A user does a search by typing the name of the class.

### Acceptance Criteria

The search starts once the user clicks the “Magnifying glass/Search” button;
The field contains a placeholder with a grey-colored text: “Введіть назву або тип гуртка”;
The placeholder disappears once the user starts typing;
Search is in Ukrainian;
Length: min.-3;  max. -1000;
Allowed characters: and [A-Я a-я 0-9 . , _ - ! @ # $ % ^ & * ( ) + = { } \ | / < > ~ ` ' : ; "] space;
The search doesn’t support English letters (characters). If the user has typed an English letter, show the warning message: “Пошук не може містити англійські літери.”

**Epic link**
E.g.: Epic #100 [Epic](https://github.com/ita-social-projects/OoS-Backend/labels/100)

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by Nikita-Babenko** [comment]
Search can support: UA/RUS/ENG language
