### ISSUE TITLE
Implement pagination for all list endpoints

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Backend#296]
Implement pagination for all **get all** endpoints for:

- [ ] Addresses
- [ ] Applications
- [ ] Chatrooms
- [ ] Chat messages (?)
- [ ] Children
- [ ] Directions
- [ ] Departments
- [ ] Classes
- [ ] Favourites
- [ ] Parents
- [ ] Providers
- [ ] Ratings
- [ ] Popular workshops & directions (statistics)
- [ ] Teachers
- [ ] Users
- [ ] Workshops

**Comment by OlhaHoliak** [comment]
ChildController with pagination PR is merged https://github.com/ita-social-projects/OoS-Backend/pull/351
