### ISSUE TITLE
OAuth & Identity Framework

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Backend#3]
**Story link**
[Registration](ita-social-projects/OoS-Backend#13)

### Task description
Investigate Identity Framework and OAuth integration with different providers (Google, Facebook, etc.)

**Comment by dmitrykiev** [comment]
Link to documentation:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio
