### ISSUE TITLE
[Date field] Date-Month digits are replaced in the 'Дата народження керівника' field when it is corrected

### ISSUE THREAD

**Issue by Findef** [ita-social-projects/OoS-Backend#300]
**Environment:** Windows 10 Home, Google Chrome 92.0.4515.159.
**Reproducible:** always.
**Build found:** 30/08/2021 12:40

**Preconditions**
A user has already started registration as a Service Provider. The 'РЕЄСТРАЦІЯ НОВОГО ЗАКЛАДУ' page is opened.

**Steps to reproduce**
1. Fill the 'Дата народження керівника' field with digits of day and month fields < 12 (e.g. 01.09.XXXX).
2. Pay attention to the location of filled digits of date and month.
2. Change digits of a year.
3. Click anywhere on the page and pay attention to the location of the Date-Month digits after that.

**Actual result**
Date-Month digits are replaced in the 'Дата народження керівника' field when it is corrected.
![bug_date_1](https://user-images.githubusercontent.com/88823354/131322250-cc97898e-fd63-476e-9fef-c56268dbb23f.png)
![bug_date_2](https://user-images.githubusercontent.com/88823354/131322295-db3de791-df71-4c89-8cfb-651ec3772476.png)

**Expected result**
Digits of the Date field stay exactly as the user wants after changing.

**User story and test case links**
([#213 Story](https://github.com/ita-social-projects/OoS-Backend/issues/213))"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by litvinets** [comment]
Fixed
