### ISSUE TITLE
[SP Class] Drop-down box with data is missing on the 'Новий гурток' create page in 'Опис' tab  in 'Напрямок за яким здійснюється навчання' field

### ISSUE THREAD

**Issue by Findef** [ita-social-projects/OoS-Backend#307]
**Environment:** Windows 10 Home, Google Chrome 92.0.4515.159.
**Reproducible:** always.
**Build found:** 31/08/2021 12:26

Preconditions
A user (Service Provider) has been registered already in the system.
(e.g.Login/pass=7gakor46280@asmm5.com/Qwer1234?)

**Steps to reproduce**
1. Loggin as Service Provider.
2. Click on the drop-down arrow to the right of the 'User Name' -> 'Мої гуртки'.
3. Click on the 'Додати гурток' button.
4. Fill mandatory fields on the 'Про гурток' tab -> click on 'Опис' tab.
5. Take a look at 'Напрямок за яким здійснюється навчання' field.

**Actual result**
The drop-down box with data is missing in 'Напрямок за яким здійснюється навчання' field.
![SP_class_DDBox_mis](https://user-images.githubusercontent.com/88823354/131479386-0fe13414-c41e-4c3d-a782-4898012ea2af.png)

**Expected result**
The drop-down box with data is present in 'Напрямок за яким здійснюється навчання' field.
![SP_class_DDBox_mis_figma](https://user-images.githubusercontent.com/88823354/131479566-7bbc3ddc-22b1-4e44-931c-5e4c795bcabd.png)

**User story and test case links**

([#55  Story](https://github.com/ita-social-projects/OoS-Backend/issues/55))"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Findef** [comment]
A Service Provider can not create new education/development sections/classes because of missing that drop-down list in that mandatory field (it is unknown what to enter).

**Comment by litvinets** [comment]
Fixed
