### ISSUE TITLE
Registration  of the service provider (NEW)

### ISSUE THREAD

**Issue by Nikita-Babenko** [ita-social-projects/OoS-Backend#312]
As a user (service provider) I want to be able to register in the application so that I could have further access to all the application’s features and member privileges.

Preconditions:
    • A user doesn’t have an account in this application yet.

Acceptance Criteria
GIVEN user wants to create a profile as Service Provider After choosing the button "Увійти/зареєструватися"
    
![2021-09-06 11_39_00-MoE _ Dev Team – Figma](https://user-images.githubusercontent.com/12609814/132187309-11b93a00-c6c8-4b94-a2d8-476e6b329f0d.png)

AND clicks the button "Зареєструватися"
![2021-09-06 11_41_09-MoE _ Dev Team – Figma](https://user-images.githubusercontent.com/12609814/132187525-78337098-3811-40ee-8c1c-acda8ac6d94e.png)

AND clicks the the button «Зареєструватися як надавач послуг»  :
AND Enters all needed data to fields    
![2021-09-06 11_43_18-MoE _ Dev Team – Figma](https://user-images.githubusercontent.com/12609814/132187856-ffefcdf5-1a17-42a6-8043-f9a20252569d.png)
AND clicks "Мені виповнилося 18 років"
AND clicks "Погоджуюсь з правилами користування та Даю згоду на оброблення персональних данних "
AND clicks "Зареєструватися "
https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-Dev-Team?node-id=279%3A0
AND page "Реєстрація нового закладу" opens
AND Enters all needed data to fields   
![2021-09-06 12_26_19-MoE _ Dev Team – Figma](https://user-images.githubusercontent.com/12609814/132194129-2775ac8f-fb02-43b3-876e-0d12d47b3151.png)
![2021-09-06 12_28_32-MoE _ Dev Team – Figma](https://user-images.githubusercontent.com/12609814/132194433-038973a0-6306-4f38-8512-a8e81aa9281f.png)
![2021-09-06 12_29_05-MoE _ Dev Team – Figma](https://user-images.githubusercontent.com/12609814/132194489-116f8430-9006-441f-ab38-94e71981a140.png)
![2021-09-06 12_29_21-MoE _ Dev Team – Figma](https://user-images.githubusercontent.com/12609814/132194546-aef5be81-c6a2-42de-9de1-df53a5859d27.png)
WHEN clicks "Зареєструвати "
![2021-09-06 12_29_53-MoE _ Dev Team – Figma](https://user-images.githubusercontent.com/12609814/132194692-52f68daf-473b-425a-9013-eecdb05c3c30.png)
THEN user redirects to the cabinet 
AND service message "Дякуємо!Ви і ваш заклад успішно зареєстровані і надіслані на перевірку адміністратора. Як тільки заклад буде підтверджено адміном, він буде видимий для усіх користувачів порталу." displayed 

![2021-09-06 12_32_52-MoE _ Dev Team – Figma](https://user-images.githubusercontent.com/12609814/132195129-8dbb4495-57c3-4da2-b928-98b987cd2965.png)

![table1-9](https://user-images.githubusercontent.com/77727618/109629382-6ceaf300-7b4c-11eb-8325-866f9f63efc4.png)
![table10-20](https://user-images.githubusercontent.com/77727618/109629391-6fe5e380-7b4c-11eb-82d6-a68c8a93e277.png)
![table21-28](https://user-images.githubusercontent.com/77727618/109629449-82f8b380-7b4c-11eb-89e4-98e87c6e72e7.png)

After pressing the button “Відмінити”, all entered data is erased and you return to the main page.

**Business rules**

1) 1 release (approval of the admin is out of scope)
2) 2,3 release (approval of the admin is mandatory)
3) If any point in obligatory information is not provided, including checkbox checking, the button "REGISTER" should be unavailable.

**Design:**
https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-Dev-Team?node-id=176%3A0

### Tasks 
1. - [ ] sample task.

**Comment by Nikita-Babenko** [comment]
https://github.com/ita-social-projects/OoS-Backend/issues/54   (OLD)

**Comment by OlhaYuzefiv** [comment]
Tasks:
1. Please add the next text to the field "Правила користування".
"Шановні батьки, на сайті автоматизованої інформаційної системи «Позашкілля» ви маєте можливість подати заяви для зарахування дитини до закладів позашкільної освіти, які наявні в системі.
Для успішної реєстрації та подачі заяви на  зарахування вам необхідно вказати достовірну інформацію.
Після подання заяви в електронному вигляді, представник закладу позашкільної освіти її опрацьовує та проводить аналіз відповідності даних в заяві та приймає рішення про зарахування або відмови (у разі конкурсного відбору) у зарахуванні дитини до закладу позашкільної освіти, із зазначенням причин такої відмови.
За результатами позитивного висновку, отриманого після проходження оцінки відповідності заяви умовам зарахування до закладу позашкільної освіти, ви зможете звернутися до обраного вами закладу позашкільної освіти для подачі оригіналів документів.» 
![правила](https://user-images.githubusercontent.com/89577816/161002611-f82e08a2-09cd-4cc8-b058-8e3572ebaf0d.jpg)
