### ISSUE TITLE
[Add more children] User is able to create more than 20 children

### ISSUE THREAD

**Issue by nastiashalavylo** [ita-social-projects/OoS-Backend#374]
**Environment:** Microsoft Windows 20H2, Mozilla Firefox 92.0.1
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/OoS-Backend/tree/main

**Preconditions**

1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="roshen@gmail.com", 'Password'="A12345a@"
3. Select 'Інформація про дитину' in menu
4. Click on 'Додати дитину' button

**Steps to reproduce**

1. Enter valid surname " Шикітка", name "Анна-Марія", parent name "Мар'янівна".
2. Write date of birth in "dd/mm/yyyy" format or choose it by clicking on a calendar icon.
3. Choose gender and choose an item from 'Оберіть соціальну групу' dropdown list
4. Click 'Додати ще одну дитину' button.
5. Repeat steps 3-5 for more than 20 times.
6. Click on 'Додаючи дані про дитину я погоджуюсь з Правилами користування та надаю згоду на обробку персональних даних' checkbox.

**Actual result**

1. More than 20 children are created; 
2. 'Кабінет користувача' page is opened;
3. No error message.

**Expected result**

1. User is not able to create more than 20 children; 
2. 'Add children' page is opened;
3. Error message appears.

**User story and test case links**
E.g.: "User story #25 
[Test case]([#149 Story](https://jira.softserve.academy/browse/OS-149))"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by DmyMi** [comment]
Hello, asked customer to clarify and they asked to remove the limit of 20 children. So technically it works as intended. Will update user story

**Comment by nastiashalavylo** [comment]
Customer asked to remove the limit of 20 children
