### ISSUE TITLE
Add Testing framework & investigate SonarQube/SonarCloud Integration

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Backend#4]
### To do 
1. - [x] Select testing framework (nUnit, xUnit, MS test)
2. - [x] Add selected framework to project
3. - [x] Investigate SonarCloud/SonarQube integration with selected testing framework (how to export test results and coverage)

**Comment by Bogdan-Hasanov** [comment]
https://github.com/SonarSource/sonarcloud-github-action
