### ISSUE TITLE
Adding information about another child in the personal account

### ISSUE THREAD

**Issue by Koshelenko-Tamara** [ita-social-projects/OoS-Backend#43]
**As a** < user > **I want to** < add the information about a child in my personal account > **so that** < I could use this application for education purposes of this child >

**Preconditions** A user has already completed a registration process and has his personal account.
A user has logged in. A child can be already registered or not.  

**Validation**

Name | Type | Condition | Validation | Error message | Comments
-- | -- | -- | -- | -- | --
Ім"я | Input field. Enabled | Mandatory | Min. 1 max. 30 characters (alphabetic and special characters ' - ) | Numeric characters and special characters (%$#@&*?!+=:"<>/) are not allowed |  
Прізвище | Input field. Enabled | Mandatory | Min. 1 max. 30 characters (alphabetic and special characters ' - ) | Numeric characters and special characters (%$#@&*?!+=:"<>/) are not allowed |  
По-батькові | Input field. Enabled | Mandatory | Min. 1 max. 30 characters (alphabetic and special characters ' - ) | Numeric characters and special characters (%$#@&*?!+=:"<>/) are not allowed |  
Додати ще | Button. Disabled |   |   |   | Enabled when all data is provided
Зберегти | Button. Disabled |   |   |   | Enabled when any changes are done
Соціальна група | Drop down list | Mandatory | Multiple selection is possible. |   | Should contain the following items: 1) Відсутня (by default);2) "Діти із багатодітних сімей"; 3)"Діти із малозабезпечених сімей"; 4)"Діти з інвалідністю"; 5) "Діти-сироти"; 6) "Діти, позбавлені батьківського піклування".

### Acceptance Criteria
1. Tapping the name of the personal account a drop down list appears which contains: 1) "Гуртки", 2) "Налаштування", "Вийти".

<img width="405" alt="Screenshot 2021-02-23 at 10 57 03" src="https://user-images.githubusercontent.com/77809312/108821219-eff8d000-75c5-11eb-9ff5-5733a0bfbdda.png">

2.  Tapping the button "НАЛАШТУВАННЯ" in the right top corner takes the user to the personal account's settings. 
3. If a user doesn't have any registered children yet, he will see the fields to be filled about a child. After filling the fields he must tap on the button "ЗБЕРЕГТИ". 
 

<img width="466" alt="Screenshot 2021-02-25 at 09 22 32" src="https://user-images.githubusercontent.com/77809312/109119098-e057c380-774c-11eb-9963-1d0839d860a7.png">
4. If a user has a registered child, but he wants to add more he must press on the button "ДОДАТИ ЩЕ". 

<img width="467" alt="Screenshot 2021-02-25 at 09 22 47" src="https://user-images.githubusercontent.com/77809312/109119152-f49bc080-774c-11eb-9abf-06a79f52a846.png">
5. Pressing the button "X" in the top corner of the second child's section must close this section.

**Epic link**
E.g.: Epic #100 [Epic](https://github.com/ita-social-projects/OoS-Backend/labels/100)

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by Nikita-Babenko** [comment]
Disable button "Зберегти" if mandatory fields are empty

**Comment by Nikita-Babenko** [comment]
**Users Age limit 120 years**

**Comment by Nikita-Babenko** [comment]
**"ІНН" Validation field:**
Length min: 10, max: 20
Allowed chars: [A-Z a-z 0-9]
Validation: invalid characters cannot be entered in the field
Format: XXXXXXXXXX
Not allowed characters: Cyrillic

**Comment by Nikita-Babenko** [comment]
**"Місце навчання ", "Місце проживання" Validation field:**
Length min: 10, max: 256
Allowed chars: [A-Z a-z 0-9 ` ' ] and space
Language: Ukrainian, Russian, English

**Comment by Nikita-Babenko** [comment]
**Fields:**
'Місце навчання',
'Місце проживання' 
'Серія та номер свідотства'. 

**Error message:** 
Text:
"Перевірте правильність заповнення данних" 
Color text:
Red
