### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by Nikita-Babenko** [ita-social-projects/OoS-Backend#456]
As a Workshop admin I want to add the Achievements to users profile so that all users will be able to know about the level of users of the service provider 

**Role**
Workshop admin 

**Precondition**
Service providers are created, workshops are created, parents applied their children to the workshops,  Workshop admin wants to add the Achievements to the user's profile so that all users will be able to know about the level of users of the service provider 

### Acceptance Criteria
SCENARIO #1 Workshop admin adds the Achievement to the users profile 
 
GIVEN Workshop admin enters the cabinet
AND opens tab “Гуртки” 

![12121](https://user-images.githubusercontent.com/12609814/144717490-05fc8615-3567-463e-a766-c3d322fcfc7b.png)
AND opens needed Workshop 
AND selects tab “Здобувачі”
AND selects the user that wants to add the achievement
AND users info-page opens
![Здобувачі 5](https://user-images.githubusercontent.com/12609814/144717744-c5c6dab9-988a-4290-a23d-36c05b1e51db.png)

![2021-12-04 18_47_49-MoE To Do's docx](https://user-images.githubusercontent.com/12609814/144717836-aedf1954-4afc-405e-95c9-3587fdb0113c.png)

AND clicks edit button “Редагувати”
AND edit page opens

![99999](https://user-images.githubusercontent.com/12609814/144717862-84e1b9d0-80dc-4704-9684-4c5b640d9d45.png)

AND selects the achievement from the dropdown list
AND inputs date
AND inputs the name of the achievement 
AND inputs name of the Coach
WHEN clicks “Зберегти”
THEN achievement is saved
AND all users can view new achievements on the tab “Про гурток” at the chapter “Досягнення
AND all users can view all achievements on the tab “Про заклад” at the chapter “Досягнення

![Досягнення 9999](https://user-images.githubusercontent.com/12609814/144717686-8af82edd-bcec-438f-9180-afb4f172fcef.png)

**Business rules**
All current achievements are displayed in the current workshop and also all achievements are displayed at the service providers tab “Про заклад”
 
 
Dropdown-fields of achievements: 
 
1)Переможці міжнародних та всеукраїнських спортивних змагань (індивідуальних та командних)
2)Призери та учасники міжнародних, всеукраїнських та призери регіональних конкурсів і виставок наукових, технічних, дослідницьких, інноваційних, ІТ проектів
3)Реципієнти міжнародних грантів
4)Призери міжнародних культурних конкурсів та фестивалів
5)Соціально активні категорії учнів
6)Цифрові інструменти Google для закладів вищої та фахової передвищої освіти
7)Переможці та учасники олімпіад міжнародного та всеукраїнського рівнів
 
List:
https://docs.google.com/spreadsheets/d/1yD1PH5b-4RjtNjNkTZYhOERCRvD3aFK71KVL2noImAw/edit#gid=813362464 
 
Information is entered by the admin 
Parents can only view
Information is visible for viewing to all admins

**Epic link**
E.g.: Epic #100 [Epic](https://github.com/ita-social-projects/OoS-Backend/labels/100)

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by litvinets** [comment]
1) display achievements in workshop-details
2) edit achievements (create new/ edit existed) from personal cabinet 
3) 1 image per record
4) replace child image
5) add new tab "досягнення" 
![image](https://user-images.githubusercontent.com/27493959/171443156-b3da2a36-d9b7-4c8e-8b8e-4052210fc93f.png)

**Comment by litvinets** [comment]
Форма додати, редагувати досягнення:
![image](https://user-images.githubusercontent.com/27493959/171452367-649a0635-117d-4534-b995-fa1b0067713e.png)
![image](https://user-images.githubusercontent.com/27493959/171452343-9ca9c3e7-f99d-48ff-adad-6b30bc0e692d.png)
