### ISSUE TITLE
Preliminary database structure

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Backend#5]
### Task description
Create preliminary UML diagrams for project's database

**Comment by Bogdan-Hasanov** [comment]
https://dbdiagram.io/d/6008814a80d742080a373073 . _Select **auto-arrange** for better view_

**Comment by Hensorskyy** [comment]
https://app.dbdesigner.net/designer/schema/0-oos-d0874012-798a-44f5-ab05-6532ea43a58d

**Comment by Elizabeth129** [comment]
https://drive.google.com/file/d/1WaPVjez5krV9WkUJgVf5mdiLOkwpULa4/view?usp=sharing

**Comment by VyacheslavDzhus** [comment]
https://dbdesigner.page.link/upXzfZtsuPHxxbCG8

чт, 21 янв. 2021 г. в 13:55, Elizabeth129 <notifications@github.com>:

**Comment by YehorOstapchuk** [comment]
https://drive.google.com/file/d/1BNcFlF4YmjFK3bH9KhrrzgkPvkmIb-da/view?usp=sharing

**Comment by mmmpolishchuk** [comment]
https://app.sqldbm.com/SQLServer/Edit/p149324/#

**Comment by YehorOstapchuk** [comment]
https://app.dbdesigner.net/designer/schema/388233
