### ISSUE TITLE
[UI] Error displaying the item "ЗАЯВИ" in the "КАБІНЕТ НАДАВАЧА" in Safari browser.

### ISSUE THREAD

**Issue by rminieiev** [ita-social-projects/OoS-Backend#528]
**Environment:** MacOS Monterey 12.1, Safari v. 15.2 (17612.3.6.1.6).
**Reproducible:** always.

**Preconditions**

1. Open link https://oos.dmytrominochkin.cloud/#
2. Log in as "Надавач"

**Steps to reproduce**

1. Click on item "ЗАЯВИ"

**Actual result**
![Screenshot 2022-01-25 at 22 18 05](https://user-images.githubusercontent.com/97878795/151059170-0b942c34-d557-4577-a084-a517faa4aa46.png)

**Expected result**
Points are displayed evenly, do not run into each other.

**Labels to be added**
"Bug", Priority ("pri: hi"), Severity ("severity:low"), Type ("UI").

**Comment by kokole110** [comment]
@LeraKornienko I've already fixed it few days ago, do you still see this bug using our repo? maybe those changes haven't been deployed yet

**Comment by rminieiev** [comment]
no, problem was fixed

**Comment by LeraKornienko** [comment]
Done
