### ISSUE TITLE
[Functional] Workshops are not displayed on the map

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Backend#529]
**Environment** macOS Big Sur 11.5.1, Chrome version 97.0.4692.71.
**Reproducible:** always

**Preconditions**
https://oos.dmytrominochkin.cloud/#/  link is opened;
It doesn't matter if the user is registered or not;
"Київ" region is selected.

**Steps to reproduce**
1. Click on "Переглянути всі" (to the right of "Найпопулярніші гуртки");
2. Click on "Карта" in the right corner;

**Actual result**
Nothing is displayed on the map. Found 0 workshops.
<img width="1424" alt="Снимок экрана 2022-01-26 в 14 46 21" src="https://user-images.githubusercontent.com/97882565/151166538-de7a84b1-ef0d-4e2e-bf7b-593ddee6864b.png">

**Expected result**
All found workshops for current location are displayed on the map.

**Labels to be added**
"Bug", Priority: medium, Severity: low, Type Functional.

**Comment by litvinets** [comment]
@OksanaGuz can you please verify it again? We cannot reproduce it anymore.
