### ISSUE TITLE
[Functional] On browser return action (chrome "return" button click) count of workshops remain not changed

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Backend#532]
**Environment:** macOS Big Sur 11.5.1, Chrome version 97.0.4692.71, Safari version 14.1.2.
**Reproducible:** always.

**Preconditions**
https://oos.dmytrominochkin.cloud/#/ link is opened;
It doesn't matter if the user is registered or not;
"Київ" region is selected.

**Steps to reproduce**
1. Click on "Переглянути всі" (to the right of "Найпопулярніші гуртки");
2. Take a look to count of workshops (in the left corner);
3. Click on "Карта" in the right corner;
4. Take a look to count of workshops (in the left corner);
5. Click on browser Return button;
6. Take a look to count of workshops (in the left corner);
7. Click on "Карта" in the right corner;
8. Click on "Список" in the right corner;
9. Take a look to count of workshops (in the left corner);

https://user-images.githubusercontent.com/97882565/151342205-a77f2145-1606-4981-815d-1fed2ea4473e.mov

**Actual result**
 "Return" browser button does not update the number of workshops. The data is updated when you click on the "Список" button,

**Expected result**
 "Return" browser button update the number of workshops.

**Labels to be added**
"Bug", "priority: medium", "severity: low", Type "Functional"

**Comment by kokole110** [comment]
@OksanaGuz bug is fixed

**Comment by OksanaGuz** [comment]
Bug has been successfully verified
