### ISSUE TITLE
[Functional] There is no "Фото" block on the "Редагування гуртка" page by Service Provider

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Backend#535]
**Environment:** macOS Big Sur 11.5.1; Chrome version 97.0.4692.71
**Reproducible:** always

**Preconditions**
Follow the link https://oos.dmytrominochkin.cloud/#/
Log into the system as Service Provider: 'Емейл’ = anna.didiaieva.95@ukr.net; 'Пароль’ = Cdby?rf95
Select «Мої гуртки» in the menu bar at the top right corner.
The “Салон краси” workshop should be in the SP Cabinet.

**Steps to reproduce**
1. Click on the “Pen” button of the existing “Салон краси” workshop.
2. Click on the “Далі” button at the bottom of the page.
"Опис" step is opened.

**Actual result**
There is no "Фото" block and no option to add a photo.

![Снимок экрана 2022-01-28 в 17 28 37](https://user-images.githubusercontent.com/97882565/151574803-01f07a29-e132-41e4-b099-a7c704db7560.png)

**Expected result**

"Photo" block is present on the page with the ability to add photos to the Workshop.

<img width="403" alt="Снимок экрана 2022-01-28 в 17 29 55" src="https://user-images.githubusercontent.com/97882565/151574831-59ca0223-50a0-4720-a8df-57551854045e.png">

**User story and test case links**
User story: https://github.com/ita-social-projects/OoS-Backend/issues/174
Test case: https://jira.softserve.academy/browse/OS-242

**Labels to be added**
"Bug", Priority: high, Severity: major, Type "Functional"

**Comment by litvinets** [comment]
@OksanaGuz It was decided that this functionality was moved to the second release. For now, photo uploading is hidden for the production.

**Comment by OksanaGuz** [comment]
Bug will be re-tested before second release.
