### ISSUE TITLE
[UI] Name of tab "Гуртки" doesn't meets design

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Backend#536]
**Environment:** macOS Big Sur 11.5.1; Chrome version 97.0.4692.71
**Reproducible:** always

**Preconditions**
Follow the link https://oos.dmytrominochkin.cloud/#/
Log into the system as Service Provider 'Емейл’ = anna.didiaieva.95@ukr.net; 'Пароль’ = Cdby?rf95
Select «Мої гуртки» in the menu bar at the top right corner.

**Steps to reproduce**
1. Examine the tabs bar for the presence of the "Гуртки" tab in the SP Cabinet

**Actual result**
There is "Мої гуртки" tab
<img width="716" alt="Снимок экрана 2022-01-30 в 13 10 35" src="https://user-images.githubusercontent.com/97882565/151697158-15fb02d0-0ed6-4488-b632-01a67c44525f.png">

**Expected result**
There should be "Гуртки" tab
<img width="509" alt="Снимок экрана 2022-01-30 в 13 09 48" src="https://user-images.githubusercontent.com/97882565/151697161-23af39bc-7001-4022-9b1a-281e05a60f48.png">

**User story and test case links**
User story: https://github.com/ita-social-projects/OoS-Backend/issues/174
Test case: https://jira.softserve.academy/browse/OS-240
**Labels to be added**
"Bug", Priority: low, Severity: trivial, Type UI.

**Comment by kokole110** [comment]
bug has been fixed

**Comment by OksanaGuz** [comment]
bug has been verified
