### ISSUE TITLE
[UI] Name of tab "Інформація про заклад" doesn't meets design

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Backend#537]
**Environment**: macOS Big Sur 11.5.1; Chrome version 97.0.4692.71
**Reproducible**: always

**Preconditions**
Follow the link https://oos.dmytrominochkin.cloud/#/
Log into the system as Service Provider 'Емейл’ = anna.didiaieva.95@ukr.net; 'Пароль’ = Cdby?rf95
Select «Інформація про організацію» in the menu bar at the top right corner.

**Steps to reproduce**
1. Take a look to "Інформація про організацію" tab

**Actual result**
There is "Інформація про організацію" name of the tab

<img width="719" alt="Снимок экрана 2022-01-30 в 13 31 45" src="https://user-images.githubusercontent.com/97882565/151697863-dc41bdcb-cfe6-43ef-af38-5f2de3edf0e3.png">

**Expected result**
There should be "Інформація про заклад" name of the tab

<img width="480" alt="Снимок экрана 2022-01-30 в 13 32 56" src="https://user-images.githubusercontent.com/97882565/151697904-602fda7d-e164-43c6-ae3a-fe6507839948.png">

**User story and test case links**
User story: #174
Test case: https://jira.softserve.academy/browse/OS-240

**Labels to be added**
"Bug", Priority: low, Severity: trivial, Type UI.

**Comment by kokole110** [comment]
@OksanaGuz bug has been fixed

**Comment by OksanaGuz** [comment]
bug has been verified
