### ISSUE TITLE
Update (approved MON) 22. entering additional child education/development sections/classes by the service provider

### ISSUE THREAD

**Issue by AnatoliiIvantsov** [ita-social-projects/OoS-Backend#55]
As a user (service provider) I want to be able to add additional child education/development sections/classes in my Cabinet so that  I can provide potential users with detailed information on the services provided.
Description
Mockup: page with title 22
https://ninjamock.com/s/QJ1HFHx
Predecessor: US #21
Preconditions:
    • A user has an account in the application and confirmed e-mail
Acceptance Criteria
    1. When user clicks the button “Додати новий гурток/секція/клас” in his cabinet, new page with text message “Будь ласка, внесіть дані:” appears containing further information for filling: table below.
 When ticking the topmost checkbox “використати контактні дані надавача освітніх послуг”, previously filled data is automatically filled again (with the ability to correct data if necessary)
![table 1-13](https://user-images.githubusercontent.com/77727618/109787537-0088f600-7c17-11eb-85cd-26265976037b.png)
![table 14-18](https://user-images.githubusercontent.com/77727618/109787572-0a125e00-7c17-11eb-86b7-1ae53e247d13.png)
![image](https://user-images.githubusercontent.com/77727618/109644056-ad06a180-7b5d-11eb-9443-b20b9067a372.png)
![image](https://user-images.githubusercontent.com/77727618/109787649-1dbdc480-7c17-11eb-8066-c96bee61a0ed.png)

    2. Selection of the direction/profile of preschool institutions is described in separate story.
    3. Фактична адреса: (We give the client a choice - fill in the fields or indicate his location on the map. In this case, the fields of the actual address are filled in automatically with the possibility of editing)
    
![table 19-21](https://user-images.githubusercontent.com/77727618/109644163-cd366080-7b5d-11eb-8048-9a0b2cb9ef77.png)
![image](https://user-images.githubusercontent.com/77727618/109644178-d3c4d800-7b5d-11eb-8036-959961ae0898.png)
   4. Викладачі:
![table 22-27](https://user-images.githubusercontent.com/77727618/109644246-e6d7a800-7b5d-11eb-82a1-dddfe51b488e.png)
![image](https://user-images.githubusercontent.com/77727618/109644257-ec34f280-7b5d-11eb-8f2d-e526b06cbde9.png)
    5. By clicking on the "Додати викладача" button, the system repeats the appearance of the fields 22-27 that the administrator must fill in.
    6. In case all the necessary data is filled, tapping on the “Створити” button saves the newly entered data.
Out of scope:
1. the personal cabinet of a service provider with a button “Додати новий гурток/секція/група” will be described in a separate story.
2. The action of the filter"Вибір напрямку/профілю" is described in a separate story.

### Tasks 
1. - [ ] sample task.

**Comment by Nikita-Babenko** [comment]
[напрямки_профілі_для_пошуку_здобувачем.xlsx](https://github.com/ita-social-projects/OoS-Backend/files/6821913/_._._._.xlsx)

**Comment by Nikita-Babenko** [comment]
Field "Вчитель" is not mandatory, because if the teacher has left the workshop we have to delete previous teacher and input data of the new teacher

**Comment by OlhaYuzefiv** [comment]
We had to chech "гурток/секція/клас".
![напрямок](https://user-images.githubusercontent.com/89577816/161292979-83a745aa-a27c-4e02-8c8c-4e513c8ca38d.jpg)

Please check if all the "гурток/секція/клас" have the right info according to the screen for the "Надавачів" 
Please check the info under the "Напрямки для надавачів послуг з їх аналогами для користувачів"
![Таблиця](https://user-images.githubusercontent.com/89577816/161293456-5cbcba05-996c-4037-b7cb-c44261e319ae.jpg)


Had to be next "Гуртки"("напрямки" on the print screen):
1. "Науково-технічний"
2. "Художньо-естетичний"
3. "Еколого-натуралистичний"
4. "Туристсько-краєзнавчий"
5. "Військово-патріотичний"
6. "Дослідницько-експерементальний"
7. "Пластово-Скаутський"
8. "Спортивний"
9. "Бібліотечно-бібліографічний"
10. "Социально-реабілітаційний"
11. "Оздоровчий"
12. "Гуманітарний"

Every "Гуртки" has own "Секції". As example "Науково-технічний гурток" has next "секції":
1. "Початково-технічний профіль" 
2. "Спортивно-технічний профіль" 
3. "Предметно-технічний профіль" 
4. "Інформацийно-технічний профіль" 
5. "Художньо-технічний профіль" 
6. "Виробничо-технічний профіль" 

Same "Секціїї" please check in another "гуртки"

And each "Секції" has its own "клас"
As example "Секція" "Початково-технічний профіль" has "клас" - "Наука і техніка".
So, please check is everything is correct according to the scheme.

**Comment by OlhaYuzefiv** [comment]
Also, please check if all "Напрямки" exists for the users.
Please check the info in the yellow place on the print screen.
![Таблиця](https://user-images.githubusercontent.com/89577816/161294797-77813fb5-0f33-4e90-b5f1-1210f6b82f89.jpg)

Please, pay attention that if you log in to the system as "ІТ, Програмування" user you had to see only "ІТ, Програмування" info from the "Напрямки для надавачів послуг з їх аналогами для користувачів"

**Comment by OlhaYuzefiv** [comment]
We do not need to add text to the "інфопідказка" but we had to leave the possibility to the tech admin to add the text in the future to the "інфоаідказка" if stakeholder will have such needs.
![напрямок](https://user-images.githubusercontent.com/89577816/161694738-af206e72-7ac6-4ffc-b627-7deb7445e8e7.jpg)

**Comment by Nikita-Babenko** [comment]
Add text "Відділ/профіль"  to the field "Відділ"

**Comment by Nikita-Babenko** [comment]
Hide field "Класс" if it has no data

**Comment by OlhaYuzefiv** [comment]
Update!

If the user(надавач) wants to register new workshop he has to choose:

1  Ministry - "МОН"
  1.1 "Назва напрямку" (please check a list in the excel)
     1.2 "Назва профілю/наукового відділення (please check list in the excel)


2 Ministry - "МКІП"
   2.1 "Назва напрямку" (please check a list in the excel)
      2.2 "Назва профілю" (please check a list in the excel)
         2.3 "Назва відділу/відділення" (please check a list in the excel)
             2.4 "Назва классу" (please check a list in the excel)

3 Ministry - "Мінспорт" 
   3.1 "Вид спорту" (please check a list in the excel)
      3.2 "Назва виду спорта" (please check a list in the excel)

4. ІНШЕ
  4.1 Назва Напрямку (please check a list in the excel)
[шаблон розбивки напрямків профілів та класів для надавачів 11.05.2022.xlsx](https://github.com/ita-social-projects/OoS-Backend/files/8670517/11.05.2022.xlsx)

**Comment by OlhaYuzefiv** [comment]
1.Workshop with the name "Фотогуртки/рукоділля" rename to "Фотогуртки". We needs to have two separate workshops "Рукоділля" та "Фотогуртки". 
<img width="614" alt="фотогуртки" src="https://user-images.githubusercontent.com/89577816/167899247-65aa9ec0-4897-4ca2-9d5a-ded664210d3d.png">
2.Workshop "цирк та кіно/фотогуртки" need rename to "Театр, цирк та кіно".
<img width="328" alt="театр цирк та кіно" src="https://user-images.githubusercontent.com/89577816/167899587-2abdcf30-a105-4791-8183-80db6a221eeb.png">
3. Workshop names should not be duplicated on the website from the user "здобувач" side. (Please check all according to the list in the excel).
[шаблон розбивки напрямків профілів та класів для надавачів 11.05.2022.xlsx](https://github.com/ita-social-projects/OoS-Backend/files/8671795/11.05.2022.xlsx)

5. Make possibility to make changes in the "міністерство", "напрямок", "профіль", "відділ" та "клас"manually till the 31.07.2022.

**Comment by OlhaYuzefiv** [comment]
Additional information:
The Technical Admin has the ability to add or change the list of ministries in the field "Сфера управління", to be able to make changes in "напрямки", "профілі" (add, edit or delete them). The provider had to have the possibility to change his  subordination in his cabinet. Only the director can change "сферу управління" (from the drop-down list). After any changes, all those involved in the changes (director, user, etc.) will receive notifications of changes.
