### ISSUE TITLE
[UI] No placeholder in email field.

### ISSUE THREAD

**Issue by rminieiev** [ita-social-projects/OoS-Backend#571]
**Environment:** MacOS v.12.2.1 (21D62), Safari v.15.3 (17612.4.9.1.8).
**Reproducible:** always.

**Preconditions**
User is not logged into website
Go to main page https://oos.dmytrominochkin.cloud/#/
Click on "УВІЙТИ/ЗАРЕЄСТРУВАТИСЯ" button in top right corner
Click on "Зареєструватися" hyperlink
Click on "Користувач" button

**Steps to reproduce**
1. Scroll down to email field

**Actual result**
No grey text placeholder in email text-box.

**Expected result**
Email testbox filled with grey text placeholder "email@companyname.com"

**Test case links**
https://jira.softserve.academy/browse/OS-337

![Screenshot 2022-02-20 at 18 38 39](https://user-images.githubusercontent.com/97878795/154854119-f9a6ec57-1863-47b8-a3d8-dd5626fe756a.png)

**Comment by litvinets** [comment]
fixed
