### ISSUE TITLE
Page of section/group

### ISSUE THREAD

**Issue by AnatoliiIvantsov** [ita-social-projects/OoS-Backend#58]
As a user (Parent role), I want to see information of the sections/groups in order to be able to select a child education/development sections for my child, write a review or a message to the service provider, add a section/group to my account
Description
Mockup: page with title 58
https://ninjamock.com/s/QJ1HFHx
Preconditions:
    • the parent chose the presented link section/group in the page of service provider
Acceptance Criteria
    1. The Section/group page should contain the following fields of output information (entered into the database by the service provider when registering in the system (US 21,22)):
«Назва Гуртка»; “Логотип”, “Телефон”, «E-mail»; «Веб-сайт»;  «Facebook»;«Instagram»; “Вік дітей: від_ до_”, “Розклад: _ заняття/тиждень”, “Дні”, “Пн, Вт, Ср, Чт, Пт, Сб, Нд”, “Вартість_грн”, “Заняття/Місяць”, “Безкоштовно”, “Наявність ресурсу для надання освіти для осіб з ООП та осіб з інвалідністю” «Опис закладу»;  icons of “Напрямки, за якими здійснюється навчання”
map with the location of the actual address; Фактична адреса закладу: “Місто”, “Вулиця”, “Будинок”
Викладачі: “Прізвище”, “Ім’я”, “По-батькові”, “Опис”, “Фото”
“Відгуки”
ability to flip through photos «Фото закладу» (at the top right of the page); 

2. When you click on a photo, a new window opens with a full-size photos view.
3.  When you click on button “Надіслати повідомлення” (only registered users can leave a review),  a new page opens with a field for filling. After filling in, the user clicks the "Надіслати" button. The message is sent to administrators from the service provider.
4. When you click on button “Додати в мій кабінет”,  a link in the form of an icon of the Section/group (presented on the service provider's page) is added to the Parent's account.
5. When you click on button “Залишити відгук”,  a new page opens with a field for filling and with “choice on a five-point system”. After filling in, the user clicks the "Додати" button. The message is sent to administrators from the service provider.

![table1-3](https://user-images.githubusercontent.com/77727618/109841342-9e99b200-7c51-11eb-9abc-6fb0bf24c733.png)
![image](https://user-images.githubusercontent.com/77727618/109841357-a35e6600-7c51-11eb-916e-305f51e8ecb3.png)
![image](https://user-images.githubusercontent.com/77727618/109841366-a5c0c000-7c51-11eb-8b3b-2371a60329ff.png)
![image](https://user-images.githubusercontent.com/77727618/109841381-a9544700-7c51-11eb-856f-4095a36c3995.png)

### Tasks 
1. - [ ] sample task.

**Comment by hanna-lenko** [comment]
Updates: 
- Mockup: https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=1%3A1364
‘Розклад занять’ element on mockup - won’t be released  
- Acc. criteria 2 “When you click on a photo, a new window opens with a full-size photos view” - won’t be released  
- Acc. criteria 4 “When you click on button “Додати в мій кабінет”… - see [story #208 (Add to favorites)](https://github.com/ita-social-projects/OoS-Backend/issues/208)
- Acc. Criteria 5 “When you click on button “Залишити відгук…” – see [story #211 (Raiting)](https://github.com/ita-social-projects/OoS-Backend/issues/211)
- 'Section/ group' = workshop (гурток)
- 'Page of service provider' (сторінка школи) feature will be discussed after 31/Jan/22
