### ISSUE TITLE
Parent Registration Update from #13

### ISSUE THREAD

**Issue by Koshelenko-Tamara** [ita-social-projects/OoS-Backend#60]
**As a user** (Parent Role) I **want to be** able to provide my personal information **so that** I could be registered in the application and use it afterwards.
**Description**

**Preconditions:**
 -  A user has already started registration by tapping on the "Sign in/Register" button. 

Validation 

Name | Type | Condition | Validation | Error message | Comments
-- | -- | -- | -- | -- | --
Ім'я | Input field. Enabled | Mandatory | Min. 1 max. 30 characters (alphabetic and special characters ' - ) | Numeric characters and special characters (%$#@&*?!+=:"<>/) are not allowed |  
Прізвище | Input field. Enabled | Mandatory | Min. 1 max. 30 characters (alphabetic and special characters ' - ) | Numeric characters and special characters (%$#@&*?!+=:"<>/) are not allowed |  
По-батькові | Input field. Enabled | Mandatory | Min. 1 max. 30 characters (alphabetic and special characters ' - ) | Numeric characters and special characters (%$#@&*?!+=:"<>/) are not allowed |  
Email | Input field. Enabled | Mandatory | Check the existence of @ character |   |  
телефон | Input field. Enabled | Mandatory | User should enter 9 numeric characters |   | autofil +380
Згода на обробку даних | Check-box. Enabled | Mandatory |   |   |  
Мені є 18 років | Check-box. Enabled | Mandatory |   |   |  
Зареєструватися | Button. Disabled |   |   |   | Enabled when all data is provided
Зареєструвати дитину | Button. Disabled |   |   |   | Enabled when all data is provided

Name | Type | Condition | Validation | Error message | Comments
-- | -- | -- | -- | -- | --
Пароль | Input field. Enabled | Mandatory | Min. 8 characters (alphabetic, numeric and special characters ' - ) |   | Enabled when all data is provided

### Acceptance Criteria
1. After tapping on "УВІЙТИ/ЗАРЕЄСТРУВАТИСЯ" button in the top right corner, a visitor is redirected to the sign-in window. 

<img width="634" alt="Screenshot 2021-03-04 at 23 23 06" src="https://user-images.githubusercontent.com/77809312/110032271-9e2c1480-7d40-11eb-8e94-c48ecde1c98b.png">

2. After tapping on the "ЗАРЕЄСТРУВАТИСЯ" button in the bottom of the window, a user is redirected to a new window: 

<img width="654" alt="Screenshot 2021-03-04 at 23 07 57" src="https://user-images.githubusercontent.com/77809312/110032350-b56b0200-7d40-11eb-93d7-97e074a59bab.png">

<img width="313" alt="Screenshot 2021-03-04 at 23 08 41" src="https://user-images.githubusercontent.com/77809312/110031901-2a8a0780-7d40-11eb-8e2e-e9b3052a9c57.png">
3. Tapping on the button "КОРИСТУВАЧ" a visitor is redirected to a page containing further obligatory information for filling: surname, name, patronymic, phone number, e-mail, password and password confirmation.

4.  After the password confirmation field a checkbox must be placed. The checkbox confirms that a user has already become 18 years old. 

5. Another line tells the user "Реєструючись я погоджуюсь з ПРАВИЛАМИ КОРИСТУВАННЯ та надаю згоду на обробку персональних даних."

6.  The line "ПРАВИЛА КОРИСТУВАННЯ" is clickable. If pressing on the button a user is redirected to a window with the site usage rules. 

7. If the customer taps on the "REGISTER" button a window disappears and he will be redirected to Google reCaptcha checking screen.

6. After successful passing of reCaptcha validation he will be redirected back to the home page where a window appears: "Лист з подальшими рекомендаціями був успішно надісланий на... (email)".

7.  Following the confirmation link in the letter he will be redirected to the home page.

**Out of scope:** Registration via different social networks (Facebook, Google, LinkedIn etc).

**Labels to be added**
"User story"

### Tasks 
1. - [ ] sample task.

**Comment by olha-sihachova** [comment]
The absence of button "Зареєструвати дитину" on the mockup of the registration page is approved by BA.
![approvig US60](https://user-images.githubusercontent.com/88825863/132253272-4a564fe3-0a34-4e2c-b428-cce7f3d667b2.jpg)

**Comment by Nikita-Babenko** [comment]
![9999](https://user-images.githubusercontent.com/12609814/133082749-4c05ce6c-79cc-4f5d-a079-8f3d3f782668.png)
Помилка! Пароль має складатися мінімум з 8-ми символів, із них одна головна літера, цифри та спецсимволи (!@#$%&*)
