### ISSUE TITLE
Implement list of subsection for Workshop description

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Backend#651]
According to design the Workshop should have a list of description subsections that include a subsection heading and subsection text.
![image](https://user-images.githubusercontent.com/24808838/171187537-a988a799-cc11-468f-ae1e-13be73543629.png)
But we currently support only single description field.

Also we should have a full text search in Elasticsearch by both subsection heading and subsection text.

We had a similar functionality (without search) added for Provider, so can see how it is implemented [in this pull request](https://github.com/ita-social-projects/OoS-Backend/pull/646)

**Comment by v08uka** [comment]
https://github.com/ita-social-projects/OoS-Backend/pull/674
