### ISSUE TITLE
Add list of options for the rate selector for paid workshops while creation/editing the workshop

### ISSUE THREAD

**Issue by Nikita-Babenko** [ita-social-projects/OoS-Backend#663]
**As a** service provider/service providers deputy/workshop admin **I want to** edit workshops pay rate **so that** to be able to change the amount

**Description**

### Acceptance Criteria
GIVEN user (service provider/service providers deputy/workshop) wants to edit workshops pay rate
AND opens workshops edit page
WHEN clicks selector
THEN list of options shall be displayed
![Selector](https://user-images.githubusercontent.com/12609814/172860008-528297ba-0914-42ed-bef4-fc5f8f245bff.png)

**Business rules:**
Option list values:
Заняття
Місяць
День
Рік
Година
Курс
Увесь період

**Epic link**
E.g.: Epic #100 [Epic](https://github.com/ita-social-projects/OoS-Backend/labels/100)

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by Illya97** [comment]
Done
