### ISSUE TITLE
We receive provider subrole in token (it could be either deputy, pr providerAdmin).

### ISSUE THREAD

**Issue by RBiyovskiy** [ita-social-projects/OoS-Backend#689]
We receive provider subrole in token (it could be either deputy, pr providerAdmin).
there is role providerAdmin - it is an administrator of a certain workshop. So, according to the req, this provider can edit/view only information according to its workshops, included applications (accept, reject, etc).
So, please, can you either send us the array of workshops id's that providerAdmin is assigned on, or on request get workshops/applications by provider id filter for us only workshops/applications for the this particular providrAdmin

_Originally posted by @litvinets in https://github.com/ita-social-projects/OoS-Frontend/issues/1173#issuecomment-1161805071_

**Comment by litvinets** [comment]
/api/v1/Application/GetByPropertyId/{property}/{id}

property - providerAdmin
id - provider admin user id

**Comment by litvinets** [comment]
current error message for unique fields - Unable to create a new provider: There is already a provider with such a data

please, change it to more general - "Fields should be unique". Maybe in addition you can send us exacrlty for was wrong? email, edproIpn, phoneNumber, etc

**Comment by litvinets** [comment]
please provider error message for creaete provider Admin if data is not unique
