### ISSUE TITLE
Registration: submit button is inactive when MiddleName is empty (though it is not required)

### ISSUE THREAD

**Issue by i-rakityanskiy** [ita-social-projects/OoS-Backend#725]
**Environment:** develop

![image](https://user-images.githubusercontent.com/75561482/177032898-870abccd-4d1e-4a13-b1d3-92e9ac9584f0.png)
![image](https://user-images.githubusercontent.com/75561482/177032909-7432f891-d290-46d8-8d85-ba91a38a6106.png)

OoS-Backend\OutOfSchool\OutOfSchool.IdentityServer\Views\Auth\Register.cshtml

**Comment by Nikita-Babenko** [comment]
If it is not mandatory - there is no need to disable the button. I shall be enabled even if there is no information in the field.
