### ISSUE TITLE
[Applications] SP does not receive new applications

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Backend#729]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Log in as parent
2. Log in as SP with workshop

**Steps to reproduce**
1. Click on "Детальніше" link of workshop
2. Click on "Подати заяву"
3. Choose child and tick checkboxes
4. Click on Apply button
5. Log in as SP with chosen workshop
6. Click on received notification
7. Observe that new application is not received
8. Log in as parent 
9. Click on "Детальніше" link of the same workshop
10. Choose the same child and make sure that application was send because user can't apply twice on the same workshop

**Actual result**
Application is send. SP received the notification but doesn't get new application

https://user-images.githubusercontent.com/97882565/177154463-ae9219a7-01be-4d94-8e8d-33ba1d4b88d2.mov

In the Parent cabinet application is also not displayed

<img width="1207" alt="Снимок экрана 2022-07-04 в 15 33 14" src="https://user-images.githubusercontent.com/97882565/177155877-15555a5e-8f8b-4708-bba1-d3edec53dc21.png">

**Expected result**

SP and Parent should see all received applications

**User story and test case links**

User story https://github.com/ita-social-projects/OoS-Backend/issues/193
Test case

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: Critical").

**Comment by litvinets** [comment]
fixed!
