### ISSUE TITLE
[AdminTools] - get Ministry admins

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Backend#793]
1) add filtartion by serach quesry
2) add pagination
![image](https://user-images.githubusercontent.com/27493959/183070396-47c340eb-59d4-42b2-b161-07a6e4ccc0bd.png)

**NOTE**
according to the designs, I see we have a tab "all", but these admins are different entities so it will be a problem to min them to one table and filter accordingly. So I suggest to remove this  table, and by default it will be the first tab on the list (in this case it will be ministry admins)
![image](https://user-images.githubusercontent.com/27493959/183070866-7b14a03b-9614-4a78-9f0a-2e99b4294900.png)

@Nikita-Babenko  please clarify the not above

**Comment by Nikita-Babenko** [comment]
It is not critical to remove tab "all" as it is displayed on the mockups - so you may just not implement it
