### ISSUE TITLE
Confirmation of registration

### ISSUE THREAD

**Issue by Lena1708** [ita-social-projects/OoS-Backend#833]
**As a user, I want to** confirm my registration **so that** I can use my account.

**Role**
user (parent role)
user (service provider)

**Precondition**
A user has registered an account 

**SCENARIO #1 A user confirms a registration directly after clicking "Зареєструватися":**
1. After registration a user opens his incoming Emails
2. A user opens the incoming Email from pozashkillia

![12](https://user-images.githubusercontent.com/54369874/187679807-eac5cc08-3482-49c7-bb9a-fb506d5ffd6e.jpg)

3. A user clicks the button „Перейдіть за посиланням“
4. A user is automatically redirected to the home page of pozashkillia

![2345](https://user-images.githubusercontent.com/54369874/187680868-aa157f01-990e-44b4-9b04-5584691f231d.jpg)

5. The text on the home page says: „Вітаємо, ви успішно зареєструвалися. Ваш логін: testlogin. Щоб керувати своїм кабінетом, будь-ласка, перейдіть за посиланням.“
6. A user clicks the button „Перейти"
![4789](https://user-images.githubusercontent.com/54369874/188199025-96a216ef-8428-48dc-9f0e-409a6ea5c0fe.jpg)

7. A user is automatically redirected to his account
![5678](https://user-images.githubusercontent.com/54369874/188199193-f2ca7fed-7e29-4916-8e97-2fae55dda723.jpg)

**SCENARIO #2 A user confirms a registration from his account:**
1. After registration a user doesn't open the incoming email from pozashkillia.
2. A user logged in to his account on pozashkillia:
![user log in](https://user-images.githubusercontent.com/54369874/192233725-4ce4ff93-e72c-47b1-879b-730a7b30e7fa.jpg)

3. User can see the red badge in the right top corner:
![user log in 2](https://user-images.githubusercontent.com/54369874/192234041-5b815b09-4d0f-4779-a5b9-949b197e9a8c.jpg)

4. A user can see the following message in his account:
"Ви ще не підтвердили свою електронну адресу. Перейдіть за посиланням внизу для підтвердження."
![Email conf red notification](https://user-images.githubusercontent.com/54369874/192236111-91cd9387-a221-43e8-8d7d-14c849a905ef.jpg)

5. A user clicks on the "Підтвердити електронну пошту" button:
![conf button click](https://user-images.githubusercontent.com/54369874/192236670-81f01a20-93f1-4eb4-867e-a6c914ce5678.jpg)

6. An Email with the confirmation registration was sent to the users' Email adress.
8. A user checks his Emails.
9. A user opens the incoming email from pozashkillia.

![12](https://user-images.githubusercontent.com/54369874/192237953-3b8fa1dc-757d-4304-a9db-dfd4e0f65c7a.jpg)

10. A user clicks the button „Перейдіть за посиланням“
11. A user is automatically redirected to the home page of pozashkillia (in the new tab)

![2345](https://user-images.githubusercontent.com/54369874/187680868-aa157f01-990e-44b4-9b04-5584691f231d.jpg)

12. The text on the home page says: „Вітаємо, ви успішно зареєструвалися. Ваш логін: testlogin. Щоб керувати своїм кабінетом, будь-ласка, перейдіть за посиланням.“
13. A user clicks the button „Перейти"
![4789](https://user-images.githubusercontent.com/54369874/188199025-96a216ef-8428-48dc-9f0e-409a6ea5c0fe.jpg)

14. A user is automatically redirected to his account
![5678](https://user-images.githubusercontent.com/54369874/188199193-f2ca7fed-7e29-4916-8e97-2fae55dda723.jpg)

**SCENARIO #3 A user confirms a registration 48 hrs. later after clicking "Зареєструватися":**
1. A user opens his incoming Emails
2. A user opens the incoming Email from pozashkillia

![12](https://user-images.githubusercontent.com/54369874/187679807-eac5cc08-3482-49c7-bb9a-fb506d5ffd6e.jpg)

3. A user clicks the button „Перейдіть за посиланням“
4. A user is automatically redirected to the home page of pozashkillia (in the new tab)

![нова лінка](https://user-images.githubusercontent.com/54369874/194143326-2afa96a3-ede1-45e5-95ee-2554cbe37d99.jpg)

5. The text on the home page says: „Термін дії посилання закінчився. Будь-ласка натисніть ПЕРЕЙТИ щоб створити нове посилання.“
6. A user clicks the button „Перейти"
7. A user is automatically redirected to his account
![Email conf red notification](https://user-images.githubusercontent.com/54369874/192236111-91cd9387-a221-43e8-8d7d-14c849a905ef.jpg)

8. A user can confirm his Email adress by clicking the "Підтвердити електронну пошту" button

**Acceptance Criteria**
1) A user clicks the button „Перейдіть за посиланням“ (The link in the button „Перейдіть за посиланням“ is valid 2 days) **[TBD]**;
2) A user is automatically redirected to the home page of pozashkillia (in the new tab);
3) After the successfull registration confirmation a user has access to all the features of his account such as changing his Email adress and changing his password.
4) As soon as a user required a new registration confirmation link, all previous confirmation registration links are considered as invalid.

Epic link
E.g.: Epic #100 [Epic](https://github.com/ita-social-projects/OoS-Backend/labels/100)

Labels to be added
"User story"

Tasks 
1. - [ ] sample task.

**Comment by valerabad** [comment]
Please add a template or site page that user will get after clicking the button "Зареєструватись"

**Comment by Lena1708** [comment]
> 1. According to the **Story Parent registration #13** 
**Parts 5.** "If the user taps on the "Register" button pop-up window disappears and he will be redirected to Google reCaptcha checking screen. 
**and Part 6.** After successful passing of reCaptcha validation user will be redirected back to the home page where a pop-up window appears: "Лист з подальшими рекомендаціями був успішно надісланий на... (email)".

A pop-up window can have the following look:
![pop-up](https://user-images.githubusercontent.com/54369874/189601607-7f555d5f-196e-40b9-85df-06e4146275e3.jpg)

> 2. User logs in:
![user log in](https://user-images.githubusercontent.com/54369874/189609533-4b503fea-87df-4d33-be31-f5edb66512c8.jpg)

User logged in. User can see the red badge in the right top corner:
![user log in 2](https://user-images.githubusercontent.com/54369874/189611332-9f107ade-f8e3-477f-930e-862f93ba2937.jpg)

User can see the following message in his account:
![user Email conf 1](https://user-images.githubusercontent.com/54369874/189612052-ebcf8db0-5f9e-488e-8755-60ada8a46c63.jpg)

**Comment by bohdanduras** [comment]
After registration when a user opens the incoming email from pozashkillia and clicks the button „Перейдіть за посиланням“ have an error massage
![image](https://user-images.githubusercontent.com/114072659/191491525-c4e70c6a-2b6a-49fa-8b86-fe6015e58f83.png)
