### ISSUE TITLE
Search results as a list/map

### ISSUE THREAD

**Issue by kechandrew** [ita-social-projects/OoS-Backend#84]
As a user, I am looking for my search results on the map or as a list

**Description**
After the user did a search on the main page, the results show as dots on the map or as a list.
![image](https://user-images.githubusercontent.com/78074355/111915667-22400500-8a80-11eb-926b-1f455bbf90ca.png)
https://ninjamock.com/s/QJ1HFHx

### Acceptance Criteria
List:
Search results show as a list in alphabetical order;
Showing results 1-20 per page;
Name, address, and contacts showed per each search result;

Map (similar to google map results):
Search results show as dots on the map with a scale of 1:500
Name of the classes showed near each relevant dot;
Search results show nearby the user location.

**Epic link**
https://www.featuremap.co/c/FAyZC6/29-%D1%8F%D0%BA-%D0%B2%D1%96%D0%B4%D0%B2%D1%96%D0%B4%D1%83%D0%B2%D0%B0%D1%87-%D0%BE%D0%B1%D0%B8%D1%80%D0%B0%D1%8E-%D0%B2%D0%B8%D0%B4-%D0%BD%D0%B0%D0%B4%D0%B0%D0%BD%D0%BD%D1%8F-%D1%96%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D1%96%D1%97-%D0%BC%D0%B0%D0%BF%D0%B0-%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by karyna-kifiuk** [comment]
Update:

Search results are displayed in a list by rating
Show results 1-12 on a page
