### ISSUE TITLE
A user has no access to all the features of his account after the successful registration confirmation

### ISSUE THREAD

**Issue by whiteand123** [ita-social-projects/OoS-Backend#861]
**Environment**: Win10 Pro; Chrome version 105.0.5195.127.
**Reproducible**: always
**Build found**: gcp-0.1.70

**Preconditions**

1. Sign up as any type of user
2. Open the incoming email from pozashkillia.

**Steps to reproduce**

1. Click the button „Перейдіть за посиланням“.
2. Click the button „Перейти".

**Actual result**
A user has no access to all the features of his account after the successful registration confirmation.

![LWR_Recording](https://user-images.githubusercontent.com/54237638/191780553-1aeaf7ae-826f-450f-97c6-8229a490e634.png)

**Expected result**
After the successfull registration confirmation a user has access to all the features of his account.

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/833

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by whiteand123** [comment]
Dublicate #858

**Comment by litvinets** [comment]
@whiteand123  fixed!
