### ISSUE TITLE
WorkShop isn't displayed in "Кабінет надавача послуг" after it's creation

### ISSUE THREAD

**Issue by val-ukr** [ita-social-projects/OoS-Backend#944]
**Environment:** https://oos.dmytrominochkin.cloud/#/
**Reproducible:** always

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP 
3. Select «Мої гуртки» in the menu bar in the top right corner.
4.  Workshop is already created  

**Steps to reproduce**
1. Open the link: https://oos.dmytrominochkin.cloud/#/personal-cabinet/provider/workshops 
2. Open DevTools (F12)
3. Refresh the page

**Actual result**
UI: The workshops don't displayed in the "Кабінет надавача послуг"
![image](https://user-images.githubusercontent.com/71636259/208872645-64193f9d-a821-436c-ae74-c840d671168a.png)

Back-end: 
Request URL: https://api.oos.dmytrominochkin.cloud/api/v1/Workshop/GetWorkshopProviderViewCardsByProviderId/00000000-0000-0000-0000-000000000000?From=0&Size=12
Request Method: GET
Status Code: 400  
Response: Provider id is empty.

**Expected result**
The Worlshop is displayed in "Кабінет користувача".
Request without the error 

**User story and test case links**
https://jira.softserve.academy/browse/OS-351

**Labels to be added**
 Severity:major, Type ("Functional").

**Comment by litvinets** [comment]
@val-ukr  bug is not reproducible
1. Log as provider 
Логін: sleep@gmail.com
Пароль: A12345a@
2. Go to personal cabinet -> My Workshops -> click on add new workshop
![image](https://user-images.githubusercontent.com/27493959/209426717-4b84f774-e2df-4ba3-b616-d6b4f73d6826.png)
3. fill in information about the new workshop  and submit
![image](https://user-images.githubusercontent.com/27493959/209426725-71568146-0e00-4b58-9b4c-202c9546f0a0.png)
5. Workshop as added to teh personal cabinet
![image](https://user-images.githubusercontent.com/27493959/209426796-d78a013f-bf49-43a5-934e-32c5e6eedd4a.png)

**Comment by val-ukr** [comment]
Логін: valeriyakononova94@gmail.com 
Пароль: Asdf1234!

**Comment by val-ukr** [comment]
The bag was fixed, I created a new account
