### ISSUE TITLE
[Parent personal information] An error is occured when storing the edited information.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Backend#945]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to OoS (https://oos.dmytrominochkin.cloud/).
2.User - Parent role is created and logged in (e.g. "Email" = '[xixofa7680@probdd.com](mailto:xixofa7680@probdd.com)', "password" = 'Qazwsx789!').
3.The location is selected (e.g. Kyiv).
4.The interested workshop (Шахмати для початківців) is found and the 'Workshop' page is opened.
5.The 'Application' page is selected (by clicking the 'Подати заяву' button).

**Steps to reproduce**
1.Select the 'Подати дані про себе' option.
2.Press the 'Редагувати' button in the 'Персональні дані' field.
3.Change the data in any of the fields.
4.Complete the edit process by clicking the 'Зберегти' button.
5.Pay attention to the error.

**Actual result**
An error is occured when storing the edited information.
![Снимок экрана 2022-12-21 113757](https://user-images.githubusercontent.com/115226563/208882031-743ffb96-e6d8-4e8a-9034-ed8ed90db6b8.jpg)
![Снимок экрана 2022-12-21 123936](https://user-images.githubusercontent.com/115226563/208888214-7d2f0511-cf71-433c-8de1-a8d35d557b6b.jpg)

**Expected result**
A user is redirected to the 'Application' page. The data that has been edited is displayed in the 'Персональні дані' field.

**User story and test case links**
["User story"(https://jira.softserve.academy/browse/OS-440)]
[Test case]([#193 Story](https://github.com/ita-social-projects/OoS-Backend/issues/193))"

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("Functional").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Bug is fixed.
